### ISSUE TITLE
Ordenar videos

### ISSUE THREAD

**Issue by lsantiago** [SmartWaterNetwork/swamp-website#13]
Agregar un criterio para ordenar los vídeos, se puede analizar en un nuevo campo que permita ordenar por antiguedad. 

![image](https://user-images.githubusercontent.com/37159/216459594-c024d47a-92ce-47c6-a10e-7129a6ae65a1.png)

**Comment by lsantiago** [comment]
Utilizar la [fecha](https://github.com/jigarius/drupal-views-sort-handler-example) como nuevo campo para organizar el contenido.

**Comment by lsantiago** [comment]
Se ordena los vídeos por la fecha de actualización. 

![image](https://user-images.githubusercontent.com/37159/221026016-3933820b-e8f8-46b9-8bca-66d102031a76.png)

**Comment by lsantiago** [comment]
@HolgerBenavides Revisar como se ordena ahora los [vídeos](http://swamp.utpl.edu.ec/?q=recursos-academicos/videos).

**Comment by HolgerBenavides** [comment]
Apreciado MSc. Santiaguito, muchas gracias por su siempre muy efectivo apoyo.
¿Existirá la posibilidad de que uno mismo al subir los videos pueda asignarles un número de orden o posición a los videos, y que con base en dicho número asignado, automáticamente se ubiquen en la posición que les corresponde?

**Comment by lsantiago** [comment]
@HolgerBenavides  A cada vídeo se ha agregado un nuevo campo **Numero_video**. Están ordenados para presentarse de forma descendente, igual esto se puede modificar. Los dos primeros que se muestran los he actualizado a modo de prueba con el id 1 y 2.

![image](https://user-images.githubusercontent.com/37159/221966763-eb5e7a2e-830f-4040-9344-80846db5beef.png)

![image](https://user-images.githubusercontent.com/37159/221988270-f8b8eb9e-3e3b-4241-9b15-dba88c7cc83c.png)
