### ISSUE TITLE
Subir imagen de integrantes de grupo de investigación.

### ISSUE THREAD

**Issue by lsantiago** [SmartWaterNetwork/swamp-website#14]
Actualizar imagen de banner de inicio con el de grupo de investigación.

**Comment by lsantiago** [comment]
Se incorpora la foto del grupo en el banner del portal. @HolgerBenavides Revisar el orden en el que aparecen. 

![image](https://user-images.githubusercontent.com/37159/221038540-01cbebc7-a5ae-46fb-83b9-f44a8db937f0.png)

**Comment by HolgerBenavides** [comment]
Muchas gracias apreciado MSc. Santiaguito. ¡Excelente!
