### ISSUE TITLE
Ingresar QR encuesta

### ISSUE THREAD

**Issue by HolgerBenavides** [SmartWaterNetwork/swamp-website#16]
Apreciado Msc. Santiaguito, buenas tardes y abundante bienestar.

Amablemente le solicito su ayuda para incluir en la plataforma SWAMP el QR de una encuesta.
Por favor ponerlo en un lugar visible y accesible.

Atentos saludos cordiales,

Holger

![Posibilidades de colaboración Ciclo del Agua ](https://user-images.githubusercontent.com/113537783/228354651-d2f79e8d-8269-49bd-8e01-537bf5ce09b3.png)

**Comment by lsantiago** [comment]
@HolgerBenavides Revisar el segundo slide, si es necesario puede abrir el navegador en modo incognito para que se pueda observar el cambio. 

![image](https://user-images.githubusercontent.com/37159/228375222-d0cf4700-5313-45dd-9725-c8203d8326fd.png)

**Comment by HolgerBenavides** [comment]
Excelente estimado Santiaguito.
¡Muchas gracias!
