### ISSUE TITLE
Material YOUTUBE para videos 

### ISSUE THREAD

**Issue by HolgerBenavides** [SmartWaterNetwork/swamp-website#6]
Apreciado MSc Santiaguito, cordial saludo y abundante bienestar junto a sus seres queridos.
Deseo para usted que todo se desarrolle con éxito y felicidad.

Amablemente le solicito que en la página web del grupo de Investigación SWN se pueda incluir en recursos académicos: http://swamp.utpl.edu.ec/?q=recursos-academicos/videos
los siguientes enlaces de videos:
 
https://youtu.be/j2umP5SYbOM
https://youtu.be/N90YaGzBJck
https://youtu.be/t7no8o4Qf0I
https://youtu.be/hZhv_VlsDT0

Además en la pestaña de "Equipo" por favor incluir la foto e información de los compañeros:
Eduardo Carrión Coronel (https://investigacion.utpl.edu.ec/es/efcarrion)
Ramiro Morocho  (https://investigacion.utpl.edu.ec/es/jrmorocho)
Silvio Aguilar (https://investigacion.utpl.edu.ec/es/sdaguilar)

**Comment by lsantiago** [comment]
@HolgerBenavides Se ha agregado los vídeos, validar si las categorías agregadas son las correctas. 

![image](https://user-images.githubusercontent.com/37159/193152386-842215f5-bc54-4de6-b87f-5be1a9885c4a.png)
