### ISSUE TITLE
Equipo de Investigadores

### ISSUE THREAD

**Issue by HolgerBenavides** [SmartWaterNetwork/swamp-website#9]
MSc. Santiaguito, buenos días y mucha paz.

Le solicito amablemente nos ayude a verificar en el equipo de Investigadores de la página del Grupo si el perfil del Dr. Fausto López y su fotografía, obtenidos del siguiente enlace:  https://investigacion.utpl.edu.ec/es/fvlopezx ha sido correctamente agregado.

Muy agradecido por su importante apoyo.

Cordialmente,

Holger

**Comment by lsantiago** [comment]
@HolgerBenavides Veo que ya logro registrar. 👍 

![image](https://user-images.githubusercontent.com/37159/197843648-4d9b88a5-96fc-4c90-bc43-658aed6da4c8.png)
